#!/bin/bash

NAME="Curupira"
ROOT="$(realpath "$(dirname "$0")")"
[ -e "$ROOT/colors.sh" ] && . "$ROOT/colors.sh" || echo "Warning: colors.sh not found, proceeding without color definitions."
#export DIALOGRC=$ROOT/dialogs/themes/green.cfg # dialog --create-rc $ROOT/.dialogrc
PARAMS="--keep-tite --exit-label Sair --ok-label OK --yes-label Sim --no-label Não --backtitle $NAME"
#dialog $PARAMETERS --title 'Curupira' --textbox $ROOT/dialogs/intro.txt 80 80

proxima=primeira

while :; do
   case "$proxima" in
      primeira)
         proxima=nome
         dialog $PARAMS --msgbox 'Bem-vindo ao pegador de dados!' 0 0
         ;;
      nome)
         anterior=primeira
         proxima=idade
         nome=$(dialog $PARAMS --stdout \
            --inputbox 'Seu nome:' 0 0)
         ;;
      idade)
         anterior=nome
         proxima=casado
         idade=$(dialog $PARAMS --stdout \
            --menu 'Qual a sua idade?' 0 0 0 \
            'menos de 15 anos' '' \
            'entre 15 e 25 anos' '' \
            'entre 25 e 40 anos' '' \
            'mais de 40 anos' '')
         ;;
      casado)
         anterior=idade
         proxima=gostos
         casado=$(dialog $PARAMS --stdout \
            --radiolist 'Estado civil:' 0 0 0 \
            'solteiro' 'livre leve solto' ON \
            'noivo' 'quase amarrado' OFF \
            'casado' 'já era' OFF \
            'viúvo' 'livre de novo' OFF)
         ;;
      gostos)
         anterior=casado
         proxima=final
         gostos=$(dialog $PARAMS --stdout \
            --separate-output \
            --checklist 'Do que você gosta?' 0 0 0 \
            'jogar futebol' '' off \
            'pescar' '' off \
            'ir ao shopping' '' off \
            'andar de bicicleta' '' off \
            'ficar na internet' '' off \
            'dormir' '' off)
         ;;
      final)
         dialog $PARAMS \
            --cr-wrap \
            --sleep 5 \
            --title 'Obrigado por responder' \
            --infobox "
                  Os dados informados foram
                  Nome  : $nome
                  Idade : $idade
                  Casado: $casado
                  Gostos: \n$gostos
                  " 14 40
         break
         ;;
      *)
         echo "Janela desconhecida '$proxima'."
         echo Abortando programa...
         exit
         ;;
   esac

   retorno=$?
   # [ $retorno -eq 1 ] && proxima=$anterior # cancelar
   [ $retorno -eq 1 ] && break # cancelar
   [ $retorno -eq 255 ] && break # Esc
done
